name: tmdb
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  device_info: ^2.0.3

  # ui
  responsive_framework: ^0.2.0
  cached_network_image: ^3.2.1
  lottie: ^1.3.0
  readmore: ^2.2.0
  # flutter_rating_bar: ^4.0.1
  # flutter_staggered_grid_view: ^0.6.2
  # carousel_slider: ^4.1.1
  flutter_svg: ^1.1.1+1

  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0

  # state management
  get: ^4.6.5

  # local storage
  get_storage: ^2.0.3

  # network
  dio: ^4.0.6
  pretty_dio_logger: ^1.1.1
  connectivity_plus: ^2.3.6

  flutter_downloader: ^1.8.1
  path_provider: ^2.0.11
  permission_handler: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mockito: ^5.2.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  build_runner:

# flutter pub run build_runner build --delete-conflicting-outputs

flutter:
  uses-material-design: true

  assets:
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
